-- The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
-- 
-- 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
--
-- Let us list the factors of the first seven triangle numbers:
--
--  1: 1
--  3: 1,3
--  6: 1,2,3,6
-- 10: 1,2,5,10
-- 15: 1,3,5,15
-- 21: 1,3,7,21
-- 28: 1,2,4,7,14,28
-- We can see that 28 is the first triangle number to have over five divisors.
-- 
-- What is the value of the first triangle number to have over five hundred divisors?

nthTriangleNumber :: Int -> Int
nthTriangleNumber n = (n*(n+1)) `div` 2

sqrt' :: Int -> Int
sqrt' n = floor $ sqrt(fromIntegral(n)) 

numDivisors :: Int -> Int
numDivisors n = (length([i | i <- [2..sqrt'(n)], n `mod` i == 0]) * 2) + 2

calc :: Int
calc = nthTriangleNumber(length(takeWhile (<500) $ map (numDivisors . nthTriangleNumber) [1..]) + 1)

main :: IO ()
main = do 
    print calc