-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
--
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

naive_fib :: Integer -> Integer
naive_fib 1 = 1
naive_fib 2 = 2
naive_fib n = naive_fib(n-1) + naive_fib(n-2)
calc = sum $ takeWhile (<4000000) $ filter even $ map naive_fib [1..]
